version: '3'

services:
#  db:
#    image: MYSQL:11.9-alpine
#    environment:
#      PGDATA: /var/lib/MYSQLql/data/pgdata
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    # Un-comment to access the db service directly
#   ports:
#     - 5432:5432
#    networks:
#      - db
#    restart: unless-stopped
#    volumes:
#      - db_data:/var/lib/MYSQLql/data

  fusionauth:
    image: ${DOCKER_HUB_USER}/fusionauth-app-mysql:latest
    depends_on:
      - db
    extra_hosts:
      - "hub.docker.internal:docker-gateway"
    environment:
      DATABASE_URL: jdbc:mysql://hub.docker.internal:3306/${FUSIONAUTH_DB_NAME}
      # Prior to version 1.19.0, use this deprecated name
      # DATABASE_ROOT_USER: ${MYSQL_USER}
      DATABASE_ROOT_USERNAME: ${MYSQL_USER}
      DATABASE_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      # Prior to version 1.19.0, use this deprecated name
      # DATABASE_USER: ${DATABASE_USER}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      # Prior to version 1.19.0, use this deprecated names
      # FUSIONAUTH_MEMORY: ${FUSIONAUTH_MEMORY}
      # FUSIONAUTH_SEARCH_ENGINE_TYPE: database
      # FUSIONAUTH_URL: http://fusionauth:9011
      # FUSIONAUTH_RUNTIME_MODE: development
      FUSIONAUTH_APP_MEMORY: ${FUSIONAUTH_APP_MEMORY}
      FUSIONAUTH_APP_RUNTIME_MODE: development
      FUSIONAUTH_APP_URL: http://fusionauth:9011
      SEARCH_TYPE: database


    networks:
     - db
    restart: unless-stopped
    ports:
      - 9011:9011
    volumes:
      - fa_config:/usr/local/fusionauth/config

networks:
  db:
    driver: bridge

volumes:
  fa_config:
